/* config_idl.h.  Generated by configure.  */

#ifndef _config_idl_h_in
#define  _config_idl_h_in 1

/* config_idl.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define to empty if the keyword does not work.  */
/* #undef const */

/* Define as __inline if that's what the C compiler calls it.  */
/* #undef inline */

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* GNU gcc/g++ provides a way to mark variables, etc. as unused */

#if defined(__GNUG__) || defined(__GNUC__)
#define not_used __attribute__ ((unused))
#else
#define not_used
#endif

/*
   $Log: config_idl.h,v $
   Revision 1.1  2004/06/22 14:02:35  schneide
   build environment for idlgif with modifications for Alpha

   Revision 1.2  2001/08/27 17:58:38  jimg
   Merged with release-3-2-3.

   Revision 1.1.2.1  2000/12/12 04:15:08  jimg
   added
 */

#endif /*  _config_idl_h_in */
